"""initial loom schema

Revision ID: 01f02779e5cd
Revises: 
Create Date: 2026-09-27 18:46:57.244625

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01f02779e5cd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_event',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=16), nullable=True),
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('account_id', sa.String(length=16), nullable=True),
    sa.Column('customer_id', sa.String(length=16), nullable=True),
    sa.Column('fields', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('override_used', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_event'))
    )
    op.create_index('ix_access_acct_t', 'access_event', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_access_emp_t', 'access_event', ['employee_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_access_event_session_id'), 'access_event', ['session_id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.String(length=16), nullable=True),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('holder_name', sa.String(length=120), nullable=False),
    sa.Column('bank_name', sa.String(length=80), nullable=False),
    sa.Column('branch_id', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by', sa.String(length=16), nullable=True),
    sa.Column('kyc_approved_by', sa.String(length=16), nullable=True),
    sa.Column('opening_mode', sa.String(length=20), nullable=True),
    sa.Column('daily_limit_paise', sa.BigInteger(), nullable=False),
    sa.Column('balance_paise', sa.BigInteger(), nullable=False),
    sa.Column('registered_mobile_tok', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_index(op.f('ix_account_customer_id'), 'account', ['customer_id'], unique=False)
    op.create_index('ix_account_kyc_opened', 'account', ['kyc_approved_by', 'opened_at'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=80), nullable=False),
    sa.Column('branch_scope', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('target', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('beneficiary',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=16), nullable=False),
    sa.Column('counterparty_account', sa.String(length=16), nullable=False),
    sa.Column('counterparty_name', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.String(length=16), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beneficiary'))
    )
    op.create_index('ix_benef_acct_t', 'beneficiary', ['account_id', 'added_at'], unique=False)
    op.create_table('branch',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branch'))
    )
    op.create_table('chain',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('root_ref', sa.String(length=24), nullable=False),
    sa.Column('employee_id', sa.String(length=16), nullable=True),
    sa.Column('account_id', sa.String(length=16), nullable=True),
    sa.Column('first_t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_s', sa.Integer(), nullable=True),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('classifier_p', sa.Float(), nullable=True),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entity_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain'))
    )
    op.create_index(op.f('ix_chain_employee_id'), 'chain', ['employee_id'], unique=False)
    op.create_index(op.f('ix_chain_kind'), 'chain', ['kind'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    op.create_index(op.f('ix_device_fingerprint'), 'device', ['fingerprint'], unique=False)
    op.create_table('employee_baseline',
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('peer_group', sa.String(length=48), nullable=False),
    sa.Column('sessions_90d', sa.Integer(), nullable=False),
    sa.Column('after20_sessions', sa.Integer(), nullable=False),
    sa.Column('peer_after20_share', sa.Float(), nullable=False),
    sa.Column('hour_rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('peer_hour_rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alibi_coverage', sa.Float(), nullable=False),
    sa.Column('accounts_approved_60d', sa.Integer(), nullable=False),
    sa.Column('approvals_baseline_60d', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id', name=op.f('pk_employee_baseline'))
    )
    op.create_table('explanation',
    sa.Column('access_event_id', sa.String(length=20), nullable=False),
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=12), nullable=False),
    sa.Column('purpose_ok', sa.Boolean(), nullable=False),
    sa.Column('timing_ok', sa.Boolean(), nullable=False),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('access_event_id', name=op.f('pk_explanation'))
    )
    op.create_index(op.f('ix_explanation_employee_id'), 'explanation', ['employee_id'], unique=False)
    op.create_index(op.f('ix_explanation_verdict'), 'explanation', ['verdict'], unique=False)
    op.create_table('model_prediction',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=24), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('entity_ref', sa.String(length=24), nullable=False),
    sa.Column('p', sa.Float(), nullable=False),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_prediction'))
    )
    op.create_index(op.f('ix_model_prediction_entity_ref'), 'model_prediction', ['entity_ref'], unique=False)
    op.create_index(op.f('ix_model_prediction_model'), 'model_prediction', ['model'], unique=False)
    op.create_table('permission',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sensitivity', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_permission'))
    )
    op.create_table('relationship',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('src_type', sa.String(length=12), nullable=False),
    sa.Column('src_id', sa.String(length=16), nullable=False),
    sa.Column('dst_type', sa.String(length=12), nullable=False),
    sa.Column('dst_id', sa.String(length=16), nullable=False),
    sa.Column('rel_type', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship'))
    )
    op.create_index(op.f('ix_relationship_dst_id'), 'relationship', ['dst_id'], unique=False)
    op.create_index(op.f('ix_relationship_src_id'), 'relationship', ['src_id'], unique=False)
    op.create_table('scenario_run',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_run'))
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=16), nullable=True),
    sa.Column('ip', sa.String(length=40), nullable=True),
    sa.Column('geo_city', sa.String(length=60), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session'))
    )
    op.create_index('ix_session_actor_start', 'session', ['actor_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_session_device_id'), 'session', ['device_id'], unique=False)
    op.create_table('signal',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('detector', sa.String(length=8), nullable=False),
    sa.Column('family', sa.String(length=8), nullable=False),
    sa.Column('version', sa.String(length=12), nullable=False),
    sa.Column('entity_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('event_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signal'))
    )
    op.create_index(op.f('ix_signal_detector'), 'signal', ['detector'], unique=False)
    op.create_index('ix_signal_entities', 'signal', ['entity_refs'], unique=False, postgresql_using='gin')
    op.create_table('state_change',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=16), nullable=False),
    sa.Column('field', sa.String(length=24), nullable=False),
    sa.Column('old_value', sa.String(length=80), nullable=True),
    sa.Column('new_value', sa.String(length=80), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.String(length=16), nullable=False),
    sa.Column('auth_method', sa.String(length=24), nullable=False),
    sa.Column('session_id', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_state_change'))
    )
    op.create_index('ix_state_acct_t', 'state_change', ['account_id', 'occurred_at'], unique=False)
    op.create_table('txn',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('from_account', sa.String(length=16), nullable=False),
    sa.Column('to_account', sa.String(length=16), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('narration', sa.String(length=120), nullable=True),
    sa.Column('branch_id', sa.String(length=16), nullable=True),
    sa.Column('session_id', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_txn'))
    )
    op.create_index('ix_txn_from_t', 'txn', ['from_account', 'occurred_at'], unique=False)
    op.create_index('ix_txn_t_brin', 'txn', ['occurred_at'], unique=False, postgresql_using='brin')
    op.create_index('ix_txn_to_t', 'txn', ['to_account', 'occurred_at'], unique=False)
    op.create_table('unmask_request',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.String(length=24), nullable=True),
    sa.Column('requested_by', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unmask_request'))
    )
    op.create_index(op.f('ix_unmask_request_employee_id'), 'unmask_request', ['employee_id'], unique=False)
    op.create_table('work_item',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('ref', sa.String(length=24), nullable=False),
    sa.Column('customer_id', sa.String(length=16), nullable=True),
    sa.Column('account_id', sa.String(length=16), nullable=True),
    sa.Column('employee_id', sa.String(length=16), nullable=True),
    sa.Column('branch_id', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_item'))
    )
    op.create_index(op.f('ix_work_item_account_id'), 'work_item', ['account_id'], unique=False)
    op.create_index(op.f('ix_work_item_customer_id'), 'work_item', ['customer_id'], unique=False)
    op.create_table('alert',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('chain_id', sa.String(length=16), nullable=False),
    sa.Column('typology', sa.String(length=40), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('lattice_rule', sa.Text(), nullable=False),
    sa.Column('dims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('argument', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recoverable', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('assignee', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scenario_tag', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], name=op.f('fk_alert_chain_id_chain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert'))
    )
    op.create_index(op.f('ix_alert_chain_id'), 'alert', ['chain_id'], unique=False)
    op.create_index(op.f('ix_alert_priority'), 'alert', ['priority'], unique=False)
    op.create_index(op.f('ix_alert_state'), 'alert', ['state'], unique=False)
    op.create_table('chain_link',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('chain_id', sa.String(length=16), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=24), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('lane', sa.String(length=8), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=True),
    sa.Column('evidence_codes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('alibi', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['chain_id'], ['chain.id'], name=op.f('fk_chain_link_chain_id_chain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_link'))
    )
    op.create_index(op.f('ix_chain_link_chain_id'), 'chain_link', ['chain_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('name_norm', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('segment', sa.String(length=16), nullable=False),
    sa.Column('address_norm', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=8), nullable=False),
    sa.Column('phone_tok', sa.String(length=40), nullable=True),
    sa.Column('kyc_tok', sa.String(length=40), nullable=True),
    sa.Column('rm_employee_id', sa.String(length=16), nullable=True),
    sa.Column('branch_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('fk_customer_branch_id_branch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index(op.f('ix_customer_phone_tok'), 'customer', ['phone_tok'], unique=False)
    op.create_index(op.f('ix_customer_pincode'), 'customer', ['pincode'], unique=False)
    op.create_index(op.f('ix_customer_rm_employee_id'), 'customer', ['rm_employee_id'], unique=False)
    op.create_index(op.f('ix_customer_segment'), 'customer', ['segment'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('pseudonym', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('branch_id', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('manager_id', sa.String(length=16), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('address_norm', sa.Text(), nullable=False),
    sa.Column('pincode', sa.String(length=8), nullable=False),
    sa.Column('phone_tok', sa.String(length=40), nullable=True),
    sa.Column('declared_relations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], name=op.f('fk_employee_branch_id_branch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee'))
    )
    op.create_index(op.f('ix_employee_branch_id'), 'employee', ['branch_id'], unique=False)
    op.create_index(op.f('ix_employee_manager_id'), 'employee', ['manager_id'], unique=False)
    op.create_index(op.f('ix_employee_role'), 'employee', ['role'], unique=False)
    op.create_table('case_file',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('alert_id', sa.String(length=24), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('assignee', sa.String(length=32), nullable=True),
    sa.Column('reviewer', sa.String(length=32), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=24), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('subject_response', sa.Text(), nullable=True),
    sa.Column('recommended_controls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_case_file_alert_id_alert'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_file'))
    )
    op.create_index(op.f('ix_case_file_alert_id'), 'case_file', ['alert_id'], unique=False)
    op.create_index(op.f('ix_case_file_state'), 'case_file', ['state'], unique=False)
    op.create_table('entitlement',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('permission_code', sa.String(length=40), nullable=False),
    sa.Column('granted_by', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_ref', sa.String(length=24), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intended_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_entitlement_employee_id_employee')),
    sa.ForeignKeyConstraint(['permission_code'], ['permission.code'], name=op.f('fk_entitlement_permission_code_permission')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement'))
    )
    op.create_index('ix_entitlement_emp_from', 'entitlement', ['employee_id', 'valid_from'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('alert_id', sa.String(length=24), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_system', sa.String(length=40), nullable=False),
    sa.Column('source_table', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=40), nullable=False),
    sa.Column('reliability', sa.String(length=1), nullable=False),
    sa.Column('credibility', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supports', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('rebuts', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alert.id'], name=op.f('fk_evidence_alert_id_alert'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_alert_id'), 'evidence', ['alert_id'], unique=False)
    op.create_table('roster',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('employee_id', sa.String(length=16), nullable=False),
    sa.Column('shift_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duty_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name=op.f('fk_roster_employee_id_employee')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roster'))
    )
    op.create_index('ix_roster_emp_start', 'roster', ['employee_id', 'shift_start'], unique=False)
    op.create_table('case_note',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('case_id', sa.String(length=24), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], name=op.f('fk_case_note_case_id_case_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_note'))
    )
    op.create_index(op.f('ix_case_note_case_id'), 'case_note', ['case_id'], unique=False)
    op.create_table('evidence_pack',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('case_id', sa.String(length=24), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case_file.id'], name=op.f('fk_evidence_pack_case_id_case_file'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_pack'))
    )
    op.create_index(op.f('ix_evidence_pack_case_id'), 'evidence_pack', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_pack_case_id'), table_name='evidence_pack')
    op.drop_table('evidence_pack')
    op.drop_index(op.f('ix_case_note_case_id'), table_name='case_note')
    op.drop_table('case_note')
    op.drop_index('ix_roster_emp_start', table_name='roster')
    op.drop_table('roster')
    op.drop_index(op.f('ix_evidence_alert_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_entitlement_emp_from', table_name='entitlement')
    op.drop_table('entitlement')
    op.drop_index(op.f('ix_case_file_state'), table_name='case_file')
    op.drop_index(op.f('ix_case_file_alert_id'), table_name='case_file')
    op.drop_table('case_file')
    op.drop_index(op.f('ix_employee_role'), table_name='employee')
    op.drop_index(op.f('ix_employee_manager_id'), table_name='employee')
    op.drop_index(op.f('ix_employee_branch_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_customer_segment'), table_name='customer')
    op.drop_index(op.f('ix_customer_rm_employee_id'), table_name='customer')
    op.drop_index(op.f('ix_customer_pincode'), table_name='customer')
    op.drop_index(op.f('ix_customer_phone_tok'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_chain_link_chain_id'), table_name='chain_link')
    op.drop_table('chain_link')
    op.drop_index(op.f('ix_alert_state'), table_name='alert')
    op.drop_index(op.f('ix_alert_priority'), table_name='alert')
    op.drop_index(op.f('ix_alert_chain_id'), table_name='alert')
    op.drop_table('alert')
    op.drop_index(op.f('ix_work_item_customer_id'), table_name='work_item')
    op.drop_index(op.f('ix_work_item_account_id'), table_name='work_item')
    op.drop_table('work_item')
    op.drop_index(op.f('ix_unmask_request_employee_id'), table_name='unmask_request')
    op.drop_table('unmask_request')
    op.drop_index('ix_txn_to_t', table_name='txn')
    op.drop_index('ix_txn_t_brin', table_name='txn', postgresql_using='brin')
    op.drop_index('ix_txn_from_t', table_name='txn')
    op.drop_table('txn')
    op.drop_index('ix_state_acct_t', table_name='state_change')
    op.drop_table('state_change')
    op.drop_index('ix_signal_entities', table_name='signal', postgresql_using='gin')
    op.drop_index(op.f('ix_signal_detector'), table_name='signal')
    op.drop_table('signal')
    op.drop_index(op.f('ix_session_device_id'), table_name='session')
    op.drop_index('ix_session_actor_start', table_name='session')
    op.drop_table('session')
    op.drop_table('scenario_run')
    op.drop_index(op.f('ix_relationship_src_id'), table_name='relationship')
    op.drop_index(op.f('ix_relationship_dst_id'), table_name='relationship')
    op.drop_table('relationship')
    op.drop_table('permission')
    op.drop_index(op.f('ix_model_prediction_model'), table_name='model_prediction')
    op.drop_index(op.f('ix_model_prediction_entity_ref'), table_name='model_prediction')
    op.drop_table('model_prediction')
    op.drop_index(op.f('ix_explanation_verdict'), table_name='explanation')
    op.drop_index(op.f('ix_explanation_employee_id'), table_name='explanation')
    op.drop_table('explanation')
    op.drop_table('employee_baseline')
    op.drop_index(op.f('ix_device_fingerprint'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_chain_kind'), table_name='chain')
    op.drop_index(op.f('ix_chain_employee_id'), table_name='chain')
    op.drop_table('chain')
    op.drop_table('branch')
    op.drop_index('ix_benef_acct_t', table_name='beneficiary')
    op.drop_table('beneficiary')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_user')
    op.drop_index('ix_account_kyc_opened', table_name='account')
    op.drop_index(op.f('ix_account_customer_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_access_event_session_id'), table_name='access_event')
    op.drop_index('ix_access_emp_t', table_name='access_event')
    op.drop_index('ix_access_acct_t', table_name='access_event')
    op.drop_table('access_event')
    # ### end Alembic commands ###
