"""scenario ground-truth labels

Revision ID: 60f0fd2f94a1
Revises: 01f02779e5cd
Create Date: 2026-09-27 19:03:09.580390

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60f0fd2f94a1'
down_revision: str | Sequence[str] | None = '01f02779e5cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenario_label',
    sa.Column('key', sa.String(length=24), nullable=False),
    sa.Column('scenario', sa.String(length=4), nullable=False),
    sa.Column('variant', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('typology', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('differing_fact', sa.Text(), nullable=True),
    sa.Column('expected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_scenario_label'))
    )
    op.create_index(op.f('ix_scenario_label_scenario'), 'scenario_label', ['scenario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_label_scenario'), table_name='scenario_label')
    op.drop_table('scenario_label')
    # ### end Alembic commands ###
